#!/bin/bash
# Build optimized zigttp with embedded bytecode for cold start benchmarking

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ZIGTTP_DIR="${ZIGTTP_DIR:-$PROJECT_DIR/../zigttp}"
HANDLER_PATH="$PROJECT_DIR/handlers/zigttp/handler.js"

echo "Building Optimized zigttp Server"
echo "================================="
echo ""
echo "Config:"
echo "  zigttp dir: $ZIGTTP_DIR"
echo "  Handler: $HANDLER_PATH"
echo ""

if [[ ! -d "$ZIGTTP_DIR" ]]; then
    echo "Error: zigttp directory not found at $ZIGTTP_DIR"
    echo "Set ZIGTTP_DIR environment variable to override"
    exit 1
fi

if [[ ! -f "$HANDLER_PATH" ]]; then
    echo "Error: Handler not found at $HANDLER_PATH"
    exit 1
fi

# Build with embedded bytecode
echo "Step 1: Compiling handler to bytecode..."
(
    cd "$ZIGTTP_DIR"
    zig build -Doptimize=ReleaseFast -Dhandler="$HANDLER_PATH"
)

# Strip symbols
echo ""
echo "Step 2: Stripping debug symbols..."
strip "$ZIGTTP_DIR/zig-out/bin/zigttp-server"

# Show results
echo ""
echo "Build complete!"
echo ""
echo "Binary info:"
ls -lh "$ZIGTTP_DIR/zig-out/bin/zigttp-server"
echo ""

# Show generated bytecode info
if [[ -f "$ZIGTTP_DIR/src/generated/embedded_handler.zig" ]]; then
    bytecode_size=$(wc -c < "$ZIGTTP_DIR/src/generated/embedded_handler.zig")
    echo "Embedded handler:"
    echo "  Bytecode file: $bytecode_size bytes"
    grep "pub const bytecode = " "$ZIGTTP_DIR/src/generated/embedded_handler.zig" | \
        sed 's/.*\[\([0-9]*\)\].*/  Bytecode array: \1 bytes/'
fi

echo ""
echo "Usage:"
echo "  $ZIGTTP_DIR/zig-out/bin/zigttp-server -p 8080"
echo ""
echo "Note: No handler file argument needed (bytecode is embedded)"
